Support Auxkernel-like updates of MFEM AuxVariables
aurora-multiphysics/platypus pull request #55
Opened 2024-11-08 14:01 UTC by alexanderianblair

MOOSE simulations commonly use `AuxVariables` for representing pre- or  post-processed fields. This PR adds support for UserObject-based `MFEMAuxKernel`s for use updating `MFEMVariable` `AuxVariables` during a solve, with an example and test demonstrated calculating a `GridFunction` defined as  the curl of an H(curl) conforming `MFEMVariable`.

2025-02-05 15:34 UTC, cmacmackin requested changes
I think this generally looks good. Most of the suggestions I make are picky grammar things.

2025-02-05 15:34 UTC, cmacmackin commented on doc/content/source/auxkernels/MFEMDivAux.md
> +FE space and storing it in a scalar elemental result variable defined on a $L^2$ FE space.
```suggestion
AuxKernel for calculating the divegence of an $H(\mathrm{div})$ conforming source variable defined on a 3D Raviart-Thomas finite element space and storing it in a scalar elemental result variable defined on an $L^2$ FE space.
```

2025-02-05 15:34 UTC, cmacmackin commented on doc/content/source/auxkernels/MFEMGradAux.md
> +a scalar elemental result variable defined on a $H(\mathrm{curl})$ conforming ND FE space.
```suggestion
AuxKernel for calculating the gradient of a scalar $H^1$ conforming source variable and storing it in
a scalar elemental result variable defined on an $H(\mathrm{curl})$ conforming Nédélec finite element space.
```

2025-02-05 15:34 UTC, cmacmackin commented on include/auxkernels/MFEMAuxKernel.h
> +  /// Pointer to result gridfunction.
```suggestion
  /// Reference to result gridfunction.
```

2025-02-05 15:34 UTC, cmacmackin commented on include/auxkernels/MFEMCurlAux.h
> +Class to set an H(div) auxvariable to be the curl of a H(curl) vector variable.
```suggestion
Class to set an H(div) auxvariable to be the curl of an H(curl) vector variable.
```

2025-02-05 15:34 UTC, cmacmackin commented on include/auxkernels/MFEMDivAux.h
> +Class to set an L2 auxvariable to be the divergence of a H(div) vector variable.
```suggestion
Class to set an L2 auxvariable to be the divergence of an H(div) vector variable.
```

2025-02-05 15:34 UTC, cmacmackin commented on include/auxkernels/MFEMCurlAux.h
> +  // Pointer to source gridfunction.
```suggestion
  // Reference to source gridfunction.
```

2025-02-05 15:34 UTC, cmacmackin commented on include/auxkernels/MFEMDivAux.h
> +  // Pointer to source gridfunction.
```suggestion
  // Reference to source gridfunction.
```

2025-02-05 15:34 UTC, cmacmackin commented on include/auxkernels/MFEMGradAux.h
> +  // Pointer to source gridfunction.
```suggestion
  // Reference to source gridfunction.
```

2025-02-05 15:34 UTC, cmacmackin commented on src/auxkernels/MFEMAuxKernel.C
> +  params.registerBase("AuxKernel");
Should you add a description?

2025-02-05 15:34 UTC, cmacmackin commented on src/auxkernels/MFEMCurlAux.C
> +      " on a H(div) conforming RT result auxvariable");
```suggestion
      "Calculates the curl of an H(curl) conforming ND source variable and stores the result"
      " on an H(div) conforming RT result auxvariable");
```

2025-02-05 15:34 UTC, cmacmackin commented on src/auxkernels/MFEMCurlAux.C
> +    _hdiv_fespace(*_result_var.ParFESpace()),
Do these actually need to be stored as class members? Can't you just access them to construct the curl operator, without saving references to them?

2025-02-05 15:34 UTC, cmacmackin commented on src/auxkernels/MFEMDivAux.C
> +      " on a L2 conforming result auxvariable");
```suggestion
      "Calculates the divergence of an H(div) conforming RT source variable and stores the result"
      " on an L2 conforming result auxvariable");
```

2025-02-05 15:34 UTC, cmacmackin commented on src/auxkernels/MFEMDivAux.C
> +    _l2_fespace(*_result_var.ParFESpace()),
Do these actually need to be stored as class members? Can't you just access them to construct the curl operator, without saving references to them?

2025-02-05 15:34 UTC, cmacmackin commented on src/auxkernels/MFEMGradAux.C
> +    _hcurl_fespace(*_result_var.ParFESpace()),
Do these actually need to be stored as class members? Can't you just access them to construct the curl operator, without saving references to them?

2025-02-07 10:32 UTC, alexanderianblair commented on src/auxkernels/MFEMDivAux.C
> +    _l2_fespace(*_result_var.ParFESpace()),
We can indeed - thanks, removed these

2025-02-07 10:33 UTC, alexanderianblair commented on test/tests/kernels/curlcurl.i
> +  []
Yup, this is much better - updated

2025-02-07 10:58 UTC, alexanderianblair commented on test/tests/kernels/diffusion.i
> +  [diffusion_gradient]
Strictly it's just the concentration gradient, - which should be equal to the Hodge dual of the diffusive flux (up to a sign) in the mug, I believe, since the `diffusivity = 1.0` in the interior of the mug.

The concentration gradient is well-defined on edges that lie exactly on the boundary, but the flux is not - physically speaking, the diffusivity is unknown outside the domain, so there's no well-defined limit for defining the diffusive flux on the boundary (mathematically, the difference is that the flux here is strictly a 2-form, whereas the concentration gradient is a 1-form). 

I agree that just having a variable labelled `diffused` to refer to the concentration is confusing here though, so I've updated this to refer to `concentration` instead!

2025-02-07 12:42 UTC, merged